baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Magic Wormhole'
assetDir = "assets"
enableInlineShortcodes = true

[menu]
[[menu.main]]
name = 'Home'
pageRef = '/'
weight = -110
[[menu.main]]
name = 'Get'
pageRef = '/get'
weight = -105
[[menu.main]]
name = 'Docs'
pageRef = '/docs'
weight = -100
